version: "2.3" # optional since v1.27.0
services:
  db:
    image: postgres:13
    volumes:
      - csci_db_vol:/var/lib/postgresql/data
      - ./sql-dump:/docker-entrypoint-initdb.d
    ports:
      - 9000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=change-in-production
      - POSTGRES_DB=csci_db
  backend:
    image: kadirbek/db_backend_hw2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=compose
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  csci_db_vol: null
